# Main playbook for MariaDB deployment
---
- name: Deploy MariaDB on database servers
  hosts: db_servers
  become: yes

  vars:
    mariadb_root_password: 'password'             
    app_db_name: 'flask_app_db'                             
    app_db_user: 'flask_user'                                
    app_db_password: 'password'                     #

  tasks:
    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Set root password (if not set)
      mysql_user:
        login_user: root
        login_password: 'password'
        user: root
        password: "{{ mariadb_root_password }}"
        host_all: true
        check_implicit_admin: true
      ignore_errors: yes

    - name: Remove anonymous MySQL users
      mysql_user:
        name: ''
        host_all: true
        state: absent
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Remove test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Create application database
      mysql_db:
        name: "{{ app_db_name }}"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Create database user for Flask app
      mysql_user:
        name: "{{ app_db_user }}"
        password: "{{ app_db_password }}"
        priv: "{{ app_db_name }}.*:ALL"
        host: '%'
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Secure MariaDB installation (optional)
      mysql_secure_installation:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        # You can add options here for further security setup
