# Variables specific to app servers
github_repo: 'https://github.com/vinod-kayartaya/flask-products-api'  
    # Replace with your repo URL
app_dir: /opt/flask_app
venv_dir: "{{ app_dir }}/venv"
env_vars:
DB_HOST: '192.168.0.21'            
DB_NAME: 'flask_app_db'
DB_USER: 'flask_user'
DB_PASSWORD: 'password'  
gunicorn_service_name: flask_gunicorn